### ISSUE TITLE
HiveTypeCompiler: Why 'DATE' to 'TIMESTAMP' conversion is needed

### ISSUE THREAD

**Issue by cabhi** [dropbox/PyHive#139]
Hi

For StrictVersion(sqlalchemy.__version__) >= StrictVersion('0.6.0'):
visit_DATE is returning 'TIMESTAMP'. Shouldn't it be DATE ?

**Comment by jingw** [comment]
I'm guessing this is because PyHive predates the DATE type, which was added in 0.12.

**Comment by cabhi** [comment]
Can it be fixed now ?

**Comment by leo-schick** [comment]
I just wonder why this is still not fixed.

I would suggest to implement this like the sqlalchemy implementation for SQL Server:
1. a new dialect member variable, e.g. `deprecated_date_type`, is added which is by default `False`/`None` and can be set manually when initializing the dialect
2. on first connection to the database, the version is read from the server via `SELECT version()`. When the version is older than 0.12, the `deprecated_date_type` variable is set to `True`
3. the type compiler uses the `DATE` type by default and uses `TIMESTAMP` when `deprecated_date_type` is `True`.

Here some code snippets from the SQL Server SQLAlchemy implementation:

![image](https://user-images.githubusercontent.com/67712864/201693109-b699c832-9855-4260-9626-35d3c22397c5.png)

![image](https://user-images.githubusercontent.com/67712864/201693082-8e608c57-8848-45dd-93d6-9124e0290608.png)
